export default [{
  'id': 'bsp-order-manager',
  'parentId': null,
  'label': '订单管理',
  'sort': 1,
  'children': [{
    'id': 'bsp-out-order-query',
    'parentId': 'bsp-order-manager',
    'label': '平台出库订单',
    'sort': 4,
    'leaf': false
  }, {
    'id': 'bsp-out-order-org-query',
    'parentId': 'bsp-order-manager',
    'label': '出库订单',
    'sort': 8,
    'children': [{
      'id': 'bsp-out-order-org-edit',
      'parentId': 'bsp-out-order-org-query',
      'label': '编辑出库订单',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-out-order-org-add',
      'parentId': 'bsp-out-order-org-query',
      'label': '新增出库订单',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-in-order-query',
    'parentId': 'bsp-order-manager',
    'label': '平台入库订单',
    'sort': 1,
    'leaf': false
  }, {
    'id': 'bsp-in-receipt-org-manager',
    'parentId': 'bsp-order-manager',
    'label': '单位入库明细',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-out-receipt-org-manager',
    'parentId': 'bsp-order-manager',
    'label': '单位出库明细',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-in-receipt-manager',
    'parentId': 'bsp-order-manager',
    'label': '平台入库明细',
    'sort': 2,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-out-receipt-manager',
    'parentId': 'bsp-order-manager',
    'label': '平台出库明细',
    'sort': 2,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-in-order-org-query',
    'parentId': 'bsp-order-manager',
    'label': '入库订单',
    'sort': 7,
    'children': [{
      'id': 'bsp-in-order-org-edit',
      'parentId': 'bsp-in-order-org-query',
      'label': '编辑入库订单',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-in-order-org-add',
      'parentId': 'bsp-in-order-org-query',
      'label': '新增入库订单',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  },
    {
      'id': 'bsp-order-org-confirm',
      'parentId': 'bsp-order-manager',
      'label': '确认单位订单',
      'sort': 8,
      'leaf': false
    }, {
      'id': 'bsp-order-org-cancel',
      'parentId': 'bsp-order-manager',
      'label': '取消单位订单',
      'sort': 8,
      'leaf': false
    }, {
      'id': 'bsp-order-org-review',
      'parentId': 'bsp-order-manager',
      'label': '复核订单',
      'sort': 8,
      'leaf': false
    },
    {
      'id': 'bsp-in-order-org-need',
      'parentId': 'bsp-order-manager',
      'label': '需求订单',
      'sort': 7,
      'leaf': false
    }
  ],
  'leaf': false
},
  {
  'id': 'bsp-stock-manager',
  'parentId': null,
  'label': '库存管理',
  'sort': 2,
  'children': [{
    'id': 'bsp-stock-org-query',
    'parentId': 'bsp-stock-manager',
    'label': '批号库存管理',
    'sort': 1,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-stock-batch-org-query',
    'parentId': 'bsp-stock-manager',
    'label': '批次库存管理',
    'sort': 2,
    'children': null,
    'leaf': true
  },{
    'id': 'bsp-stock-query',
    'parentId': 'bsp-stock-manager',
    'label': '平台批号库存管理',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-stock-batch-query',
    'parentId': 'bsp-stock-manager',
    'label': '平台批次库存管理',
    'sort': 4,
    'children': null,
    'leaf': true
  },
    {
      'id': 'org-logistics-manager',
      'parentId': 'bsp-stock-manager',
      'label': '物流中心管理',
      'sort': 1,
      'children': [{
        'id': 'org-logistics-edit',
        'parentId': 'org-logistics-manager',
        'label': '编辑物流中心',
        'sort': 3,
        'children': null,
        'leaf': true
      }, {
        'id': 'org-logistics-query',
        'parentId': 'org-logistics-manager',
        'label': '查看物流中心',
        'sort': 1,
        'children': null,
        'leaf': true
      }, {
        'id': "'org-logistics-add",
        'parentId': 'org-logistics-manager',
        'label': '新增物流中心',
        'sort': 2,
        'children': null,
        'leaf': true
      }, {
        'id': 'org-logistics-delete',
        'parentId': 'org-logistics-manager',
        'label': '删除物流中心',
        'sort': 4,
        'children': null,
        'leaf': true
      },
        {
          id: 'org-warehouse-add',
          label: '添加仓库'
        }, {
          id: 'org-warehouse-edit',
          label: '编辑仓库'
        }, {
          id: 'org-warehouse-delete',
          label: '删除仓库'
        },{
          id: 'org-warehouse-dev-query',
          label: '查看仓库设备'
        }],
      'leaf': false
    }],
  'leaf': false
}, {
  'id': 'system-config',
  'parentId': null,
  'label': '系统设置',
  'sort': 3,
  'children': [{
    'id': 'bsp-system-log',
    'parentId': 'bsp-system-config',
    'label': '系统日志',
    'sort': 5,
    'children': null,
    'leaf': true
  }, {
    'id': 'access-role-manager',
    'parentId': 'bsp-system-config',
    'label': '角色管理',
    'sort': 4,
    'children': [{
      'id': 'bsp-access-platfrom-role-export',
      'parentId': 'bsp-user-role-manager',
      'label': '用户角色分配导出',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-watch',
      'parentId': 'bsp-user-role-manager',
      'label': '查看角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-access-platfrom-permission-export',
      'parentId': 'bsp-user-role-manager',
      'label': '角色权限导出',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-add',
      'parentId': 'bsp-user-role-manager',
      'label': '新增角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-access-role-start',
      'parentId': 'bsp-user-role-manager',
      'label': '启用角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-access-role-delete',
      'parentId': 'bsp-user-role-manager',
      'label': '删除角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-edit',
      'parentId': 'bsp-user-role-manager',
      'label': '编辑角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-access-role-stop',
      'parentId': 'bsp-user-role-manager',
      'label': '停用角色',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-push-traceorder-address-manager',
    'parentId': 'bsp-system-config',
    'label': '订单信息推送地址配置',
    'sort': 1,
    'children': [{
      'id': 'bsp-oauth-client-details-watch',
      'parentId': 'bsp-push-traceorder-address-manager',
      'label': '查看API账号',
      'sort': 5,
      'children': null,
      'leaf': true
    }, {
      'id': 'traceorder-push-address-query',
      'parentId': 'bsp-push-traceorder-address-manager',
      'label': '查看订单信息推送地址配置',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'traceorder-push-address-edit',
      'parentId': 'bsp-push-traceorder-address-manager',
      'label': '编辑订单信息推送地址配置',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'traceorder-push-address-add',
      'parentId': 'bsp-push-traceorder-address-manager',
      'label': '新增订单信息推送地址配置',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'traceorder-push-address-delete',
      'parentId': 'bsp-push-traceorder-address-manager',
      'label': '删除订单信息推送地址配置',
      'sort': 4,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-platform-user-manager',
    'parentId': 'bsp-system-config',
    'label': '用户管理',
    'sort': 3,
    'children': [{
      'id': 'bsp-department-delete',
      'parentId': 'bsp-platform-user-manager',
      'label': '删除部门',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-platform-user-edit',
      'parentId': 'bsp-platform-user-manager',
      'label': '编辑用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-department-edit',
      'parentId': 'bsp-platform-user-manager',
      'label': '修改部门',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-platform-user-watch',
      'parentId': 'bsp-platform-user-manager',
      'label': '查看用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-department-add',
      'parentId': 'bsp-platform-user-manager',
      'label': '新增部门',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-platform-user-add',
      'parentId': 'bsp-platform-user-manager',
      'label': '新增用户',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-attachment-name-update',
    'parentId': 'bsp-system-config',
    'label': '编辑附件名称',
    'sort': 7,
    'children': null,
    'leaf': true
  }, {
    'id': 'bsp-push-address-manager',
    'parentId': 'bsp-system-config',
    'label': '单位推送地址配置',
    'sort': 1,
    'children': [{
      'id': 'bsp-push-address-edit',
      'parentId': 'bsp-push-address-manager',
      'label': '编辑单位推送地址配置',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-push-address-query',
      'parentId': 'bsp-push-address-manager',
      'label': '查看单位推送地址配置',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-push-address-add',
      'parentId': 'bsp-push-address-manager',
      'label': '新增单位推送地址配置',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-push-address-delete',
      'parentId': 'bsp-push-address-manager',
      'label': '删除单位推送地址配置',
      'sort': 4,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-organization-user-manager',
    'parentId': 'bsp-system-config',
    'label': '单位用户管理',
    'sort': 2,
    'children': [{
      'id': 'bsp-org-user-add',
      'parentId': 'bsp-organization-user-manager',
      'label': '新增单位用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-org-user-edit',
      'parentId': 'bsp-organization-user-manager',
      'label': '编辑单位用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'bsp-org-user-watch',
      'parentId': 'bsp-organization-user-manager',
      'label': '查看单位用户',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'bsp-push-log-org-query',
    'parentId': 'bsp-system-config',
    'label': '订单推送日志',
    'sort': 6,
    'children': null,
    'leaf': true
  }],
  'leaf': false
  }];
