export default [
  {
    'id': 'base-data-manager',
    'parentId': null,
    'label': '基础资料',
    children: [
      {
        'id': 'mdm-operating-goods-manager',
        'parentId': null,
        'label': '经营货品',
        'sort': 3,
        'children': [
          {
            'id': 'mdm-operating-goods-watch',
            'parentId': 'mdm-operating-goods-manager',
            'label': '查看经营货品',
            'sort': null,
            'children': null,
            'leaf': true
          }, {
            'id': 'mdm-operating-goods-delete',
            'parentId': 'mdm-operating-goods-manager',
            'label': '删除经营货品',
            'sort': null,
            'children': null,
            'leaf': true
          }, {
            'id': 'mdm-operating-goods-add',
            'parentId': 'mdm-operating-goods-manager',
            'label': '新增经营货品',
            'sort': null,
            'children': null,
            'leaf': true
          }],
        'leaf': false
      },
      {
        'id': 'code-batch-number-manager',
        'parentId': 'code-data-manager',
        'label': '批号管理',
        'sort': 4,
        'children': [{
          'id': 'mdm-batchNumber-add',
          'parentId': 'code-batch-number-manager',
          'label': '新增批号',
          'sort': 2,
          'children': null,
          'leaf': true
        }, {
          'id': 'mdm-batchNumber-delete',
          'parentId': 'code-batch-number-manager',
          'label': '删除批号',
          'sort': 4,
          'children': null,
          'leaf': true
        }, {
          'id': 'code-batch-number-query',
          'parentId': 'code-batch-number-manager',
          'label': '查询批号',
          'sort': 1,
          'children': null,
          'leaf': true
        }, {
          'id': 'mdm-batchNumber-file-upload',
          'parentId': 'code-batch-number-manager',
          'label': '批号文件上传',
          'sort': 4,
          'children': null,
          'leaf': true
        }, {
          'id': 'mdm-batchNumber-update',
          'parentId': 'code-batch-number-manager',
          'label': '编辑批号',
          'sort': 3,
          'children': null,
          'leaf': true
        }],
        'leaf': false
      }
    ]
  },{
  'id': 'code-data-manager',
  'parentId': null,
  'label': '追溯码数据',
  'sort': 1,
  'children': [
    {
    'id': 'goods-codes-upload',
    'parentId': 'code-data-manager',
    'label': '源文件上传',
    'sort': 1,
    'children': [{
      'id': 'codes-file-upload',
      'parentId': 'goods-codes-upload',
      'label': '新增源文件上传',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'codes-file-bind-share-domain',
      'parentId': 'goods-codes-upload',
      'label': '数据共享域名',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'codes-file-query',
      'parentId': 'goods-codes-upload',
      'label': '查看源文件上传',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'codes-file-bind-delete',
      'parentId': 'goods-codes-upload',
      'label': '删除关联关系',
      'sort': 4,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'biz-codes-upload',
    'parentId': 'code-data-manager',
    'label': '业务追溯上传',
    'sort': 3,
    'children': [{
      'id': 'biz-codes-file-query',
      'parentId': 'biz-codes-upload',
      'label': '查看业务追溯上传信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'biz-codes-file-upload',
      'parentId': 'biz-codes-upload',
      'label': '新增业务追溯上传',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'exception-codes-upload',
    'parentId': 'code-data-manager',
    'label': '异常追溯上传',
    'sort': 2,
    'children': [{
      'id': 'exception-codes-file-query',
      'parentId': 'exception-codes-upload',
      'label': '查看异常追溯上传信息',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'exception-codes-file-upload',
      'parentId': 'exception-codes-upload',
      'label': '新增异常追溯文件上传',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'exception-codes-goods-upload',
      'parentId': 'exception-codes-upload',
      'label': '通过货品、批号新增异常追溯',
      'sort': 2,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  },
    {
    'id': 'gs1-rule-manager',
    'parentId': 'code-data-manager',
    'label': 'GS1编制结构管理',
    'sort': 5,
    'children': [
      {
      'id': 'gs1-rule-edit',
      'parentId': 'gs1-rule-manager',
      'label': '编辑GS1编制结构',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'gs1-rule-delete',
      'parentId': 'gs1-rule-manager',
      'label': '删除GS1编制结构',
      'sort': 4,
      'children': null,
      'leaf': true
    }, {
      'id': 'gs1-rule-add',
      'parentId': 'gs1-rule-manager',
      'label': '新增GS1编制结构',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'gs1-rule-query',
      'parentId': 'gs1-rule-manager',
      'label': '查询GS1编制结构',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  },
    {
      'id': 'electron-code-rule-manager',
      'parentId': 'code-data-manager',
      'label': '电子监管码编制结构管理',
      'sort': 5,
      'children': [
        {
          'id': 'electron-code-rule-edit',
          'parentId': 'electron-code-rule-manager',
          'label': '编辑电子监管码编制结构',
          'sort': 3,
          'children': null,
          'leaf': true
        }, {
          'id': 'electron-code-rule-delete',
          'parentId': 'electron-code-rule-manager',
          'label': '删除电子监管码编制结构',
          'sort': 4,
          'children': null,
          'leaf': true
        }, {
          'id': 'electron-code-rule-add',
          'parentId': 'electron-code-rule-manager',
          'label': '新增电子监管码编制结构',
          'sort': 2,
          'children': null,
          'leaf': true
        }, {
          'id': 'electron-code-rule-query',
          'parentId': 'electron-code-rule-manager',
          'label': '查询电子监管码编制结构',
          'sort': 1,
          'children': null,
          'leaf': true
        }],
      'leaf': false
    }
  ],
  'leaf': false
}, {
  'id': 'code-trace-manager',
  'parentId': null,
  'label': '追溯查询',
  'sort': 2,
  'children': [{
    'id': 'code-injection-trace',
    'parentId': 'code-trace-manager',
    'label': '终端使用/销售记录',
    'sort': 4,
    'children': null,
    'leaf': true
  }, {
      'id': 'batch-number-trace',
      'parentId': 'code-trace-manager',
      'label': '批号追溯',
      'sort': 2,
      'children': [{
        'id': 'batch-number-trace-query',
        'parentId': 'batch-number-trace',
        'label': '查看批号追溯',
        'sort': 1,
        'children': null,
        'leaf': true
      }, {
        'id': 'batch-number-trace-add',
        'parentId': 'batch-number-trace',
        'label': '新增批号追溯任务',
        'sort': 1,
        'children': null,
        'leaf': true
      }],
      'leaf': false
    },{
    'id': 'code-trace-query',
    'parentId': 'code-trace-manager',
    'label': '追溯码追溯查询',
    'sort': 1,
    'children': [{
      'id': 'single-code-trace-query',
      'parentId': 'code-trace-query',
      'label': '查询单只追溯码',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-injection-query',
      'parentId': 'code-trace-query',
      'label': '查询接种日志信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-log-delete',
      'parentId': 'code-trace-query',
      'label': '删除追溯码日志',
      'sort': 1,
      'children': null,
      'leaf': true
    },{
      'id': 'code-trace-query-all',
      'parentId': 'code-trace-query',
      'label': '查询所有的追溯码日志信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-query-goods-all',
      'parentId': 'code-trace-query',
      'label': '查询所有货品的追溯码日志信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-exception-query',
      'parentId': 'code-trace-query',
      'label': '查询异常日志信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'wechat-single-code-trace-query',
      'parentId': 'code-trace-query',
      'label': '微信小程序查询单只追溯码',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-json-download',
      'parentId': 'code-trace-query',
      'label': '下载json数据',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-trace-inventory-surplus-query',
      'parentId': 'code-trace-query',
      'label': '查询盘盈入库日志信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'code-biz-trace',
    'parentId': 'code-trace-manager',
    'label': '业务追溯查询',
    'sort': 3,
    'children': [{
      'id': 'code-biz-log-push',
      'parentId': 'code-biz-trace',
      'label': '推送数据',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-biz-trace-insert-code',
      'parentId': 'code-biz-trace',
      'label': '录入追溯码日志',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-biz-trace-delete-code',
      'parentId': 'code-biz-trace',
      'label': '删除追溯码日志',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'system-config',
  'parentId': null,
  'label': '系统管理',
  'sort': 3,
  'children': [{
    'id': 'code-system-log-query',
    'parentId': 'code-system-manager',
    'label': '系统日志',
    'sort': 5,
    'children': null,
    'leaf': true
  }, {
    'id': 'code-account-manager',
    'parentId': 'code-system-manager',
    'label': '账户管理',
    'sort': 4,
    'children': [{
      'id': 'code-account-query',
      'parentId': 'code-account-manager',
      'label': '查看账户',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-account-add',
      'parentId': 'code-account-manager',
      'label': '新增账户',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'code-account-edit',
      'parentId': 'code-account-manager',
      'label': '编辑账户',
      'sort': 2,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  },
    {
    'id': 'access-role-manager',
    'parentId': 'code-system-manager',
    'label': '角色管理',
    'sort': 3,
    'children': [{
      'id': 'codes-access-role-start',
      'parentId': 'codes-user-role-manager',
      'label': '启用角色',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-edit',
      'parentId': 'codes-user-role-manager',
      'label': '编辑角色',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'codes-access-role-stop',
      'parentId': 'codes-user-role-manager',
      'label': '停用角色',
      'sort': 4,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-add',
      'parentId': 'codes-user-role-manager',
      'label': '新增角色',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'codes-access-role-delete',
      'parentId': 'codes-user-role-manager',
      'label': '删除角色',
      'sort': 5,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-watch',
      'parentId': 'codes-user-role-manager',
      'label': '查看角色',
      'sort': 6,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'code-attachment-name-update',
    'parentId': 'code-system-manager',
    'label': '编辑附件名称',
    'sort': 9,
    'children': null,
    'leaf': true
  }, {
    id: 'code-access-manager',
    label: '货品追溯权限分配',
    children: [
      {
        id: 'code-access-add',
        label: '新增货品追溯权限'
      },
      {
        id: 'code-access-query',
        label: '查看货品追溯权限'
      },
      {
        id: 'code-access-delete',
        label: '删除货品追溯权限'
      },
    ]
  }],
  'leaf': false
}];
