stages:
  - test
  - build
  - deploy

# 所有 stage 之前的操作
before_script:
  - npm set registry https://registry.npm.taobao.org
  - npm install

# 代码检查
lint:
  stage: test
  script: npm run lint

local-build:
  stage: build
  tags:
    - node
  script:
    - npm run build
    - scp -r dist/* root@172.25.10.10:/opt/dev-web-dist/lantern-web
    
